grpc:
  client:
    user-service:
      address: static://localhost:9000
      negotiationType: plainText
    order-service:
      address: static://localhost:9001
      negotiationType: plainText
server:
  port: 8081
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security-jwt-config:
  jwtExpirationMs: 86400000
  jwtSecret: encryptoWearMyWorstAreaIsChoosingASecretAndWellEnough!@
file-server:
  cloudinary:
    api-key: 813943829169579
    api-secret: xADVTKxM0bwPV2BOEVQxCtoq5Kw
    cloud-name: adavuruku

