spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: grpc-db
      port: 27017
      host: localhost
      auto-index-creation: true
#      uri: mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
grpc:
  server:
    port: 9000