spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: grpc-db
      port: 27017
      host: localhost
grpc:
  server:
    port: 9000